"""empty message

Revision ID: 58d9cfb65b3c
Revises: ee9bbd372651
Create Date: 2020-01-17 17:52:41.270333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d9cfb65b3c'
down_revision = 'ee9bbd372651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_grats')
    op.drop_table('user_entries')
    op.drop_table('prompt_entries')
    op.add_column('entry', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('gratitude', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gratitude', 'created_at')
    op.drop_column('entry', 'created_at')
    op.create_table('prompt_entries',
    sa.Column('entry_id', sa.INTEGER(), nullable=True),
    sa.Column('prompt_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], )
    )
    op.create_table('user_entries',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('entry_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('user_grats',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('grat_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['grat_id'], ['gratitude.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
