"""empty message

Revision ID: c6c70a17dc4c
Revises: 5f052aafc6ba
Create Date: 2019-11-04 20:27:32.067813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c70a17dc4c'
down_revision = '5f052aafc6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gratitude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('response', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gratitude_user_id'), 'gratitude', ['user_id'], unique=False)
    op.drop_index('ix_entry_user_id', table_name='entry')
    op.create_index(op.f('ix_entry_user_id'), 'entry', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_user_id'), table_name='entry')
    op.create_index('ix_entry_user_id', 'entry', ['user_id'], unique=1)
    op.drop_index(op.f('ix_gratitude_user_id'), table_name='gratitude')
    op.drop_table('gratitude')
    # ### end Alembic commands ###
